config/routes.rb
Rails.application.routes.draw do
  get "users/index"
  get "users/show"
  devise_for :users
  resources :events, only: [:index, :show, :new, :create]
  resources :users, only: [:index, :show]
  resources :attendances, only: [:create]
  resources :invitations, only: [:create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attended_event, class_name: "Event"
  belongs_to :attendee, class_name: "User"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :host, class_name: "User"
  has_many :attendances, foreign_key: :attended_event_id
  has_many :attendees, through: :attendances, foreign_key: "attended_event_id",
           class_name: "User", source: :attendee
  has_many :invitations, foreign_key: :invited_event_id
  has_many :invitees, through: :invitations, foreign_key: "invited_event_id",
           class_name: "User", source: :invitee
  validates :name, presence: true
  validates :location, presence: true
  validates :date, presence: true

  scope :past, -> { where("date < ?", Time.now) }
  scope :future, -> { where("date > ?", Time.now) }

end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :invited_event, class_name: "Event"
  belongs_to :invitee, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :hosted_events, foreign_key: "host_id", class_name: "Event"
  has_many :attendances, foreign_key: :attendee_id
  has_many :attended_events, through: :attendances, foreign_key: "attendee_id",
           class_name: "Event", source: :attended_event
  has_many :invitations, foreign_key: :invitee_id
  has_many :invited_events, through: :invitations, foreign_key: "invitee_id",
           class_name: "Event", source: :invited_event
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @attendance = Attendance.new(attendance_params)
    if @attendance.save
      Invitation.find_by(invitee_id: attendance_params[:attendee_id], invited_event_id: attendance_params[:attended_event_id]).destroy
      redirect_to user_path(current_user), notice: "Attendance confirmed."
    else
      redirect_to events_path, notice: "Attendance not registered."
    end

  end

  private

  def attendance_params
    params.require(:attendance).permit(:attended_event_id, :attendee_id)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :show]

  def index
    @events = Event.order(:date)
  end

  def show
    @event = Event.find(params[:id])
    @invitees = User.where.not(id: [current_user.id] + @event.attendee_ids).order(:name)
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.hosted_events.build(event_params)
    if @event.save
      redirect_to events_path, notice: "Event created successfully."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :location, :date)
  end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    if Invitation.exists?(invitation_params)
      redirect_to event_path(invitation_params[:invited_event_id]), notice: "You already invited this user for this event."
    else
      @invitation = Invitation.new(invitation_params)
      if @invitation.save
        redirect_to event_path(@invitation.invited_event), notice: "Invitation sent."
      else
        redirect_to event_path(@invitation.invited_event), notice: "Invitation not sent."
      end
    end

  end

  private

  def invitation_params
    params.require(:invitation).permit(:invited_event_id, :invitee_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>All Events</h1>

<h2>Upcoming Events</h2>
<% if @events.future.any? %>
  <ul>
    <% @events.future.each do |event| %>
      <li>
        <strong><%= link_to(event.name, event_path(event)) %></strong>
        | hosted by: <%= link_to(event.host.name, user_path(event.host)) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No past events found.</p>
<% end %>

<h2>Past Events</h2>
<% if @events.past.any? %>
  <ul>
    <% @events.past.each do |event| %>
      <li>
        <strong><%= link_to(event.name, event_path(event)) %></strong>
        | hosted by: <%= link_to(event.host.name, user_path(event.host)) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No past events found.</p>
<% end %>

<p>
  <%= link_to "Create New Event", new_event_path, class: "btn" %>
</p>

app/views/events/new.html.erb
<h1>New Event</h1>

<% if @event.errors.any? %>
  <h3><%= pluralize(@event.errors.count, "error") %> prevented this event from being saved:</h3>
  <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @event do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </p>

  <p>
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </p>

  <p>
    <%= f.submit "Create Event" %>
  </p>
<% end %>

<p><%= link_to "Back to events", events_path %></p>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<p><strong>Location:</strong> <%= @event.location %></p>
<p><strong>Date:</strong> <%= @event.date&.strftime("%B %d, %Y") %></p>
<p><strong>Hosted by:</strong> <%= link_to(@event.host.name, user_path(@event.host)) %></p>

<h2>Attendees</h2>

<% if @event.attendees.any? %>
  <ul>
    <% @event.attendees.each do |user| %>
      <li>
        <%= link_to(user.name, user_path(user)) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No attendees yet.</p>
<% end %>


<p>
<% if current_user == @event.host %>
    <%= form_with model: Invitation.new do |f| %>
      <%= f.hidden_field :invited_event_id, value: @event.id %>
      <strong><%= f.label :invitee_id, "Invite someone" %></strong><br>
      <%= f.collection_select :invitee_id, @invitees, :id, :name, prompt: "Select a user" %><br>
    </div>

    <%= f.submit "Invite" %>
  <% end %>
<% end %>
</p>

</p>
<% if @event.invitees.exists?(current_user.id) %>
  <%= button_to "Accept invitation", attendances_path,
                params: { attendance: {
                  attended_event_id: @event.id,
                  attendee_id: current_user}
                } %>
<% end %>
</p>

<p>
  <%= link_to "Back to events", events_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "shared/navbar" %>

    <% flash.each do |key, message| %>
      <div class="flash <%= key %>">
        <%= message %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <%= link_to "Events", events_path, class: ("nav-link " + (current_page?(events_path) ? "active" : "")) %>

  <% if user_signed_in? %>
    <%= link_to "Profile", current_user, class: "nav-link" %>
    <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
    <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
  <% end %>
</nav>

app/views/users/index.html.erb
<h1>Users</h1>

<% if @users.any? %>
  <ul>
    <% @users.each do |user| %>
      <li>
        <%= link_to(user.name, user_path(user)) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No users found.</p>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<p><strong>Email:</strong> <%= @user.email %></p>

<p><strong>Hosted Events:</strong></p>

<% if @user.hosted_events.any? %>
  <ul>
    <% @user.hosted_events.each do |event| %>
      <li>
        <%= link_to(event.name, event_path(event)) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>User is not hosting any events.</p>
<% end %>


<p><strong>Past attended events:</strong></p>
<% past_events = @user.attended_events.where(date: ..Time.now) %>

<% if past_events.any? %>
  <ul>
    <% past_events.each do |event| %>
      <li>
        <%= link_to(event.name, event_path(event)) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No past events.</p>
<% end %>


<p><strong>Future attended events:</strong></p>
<% future_events = @user.attended_events.where(date: Time.now..) %>

<% if future_events.any? %>
  <ul>
    <% future_events.each do |event| %>
      <li>
        <%= link_to(event.name, event_path(event)) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No future events.</p>
<% end %>